FUEL_INTERVAL_MILES = 1000
FUEL_STOP_HOURS = 0.5
PICKUP_DROP_HOURS = 1
AVG_SPEED_MPH = 65
DAILY_MAX_ON_DUTY = 14
DAILY_MAX_DRIVING = 11
OFF_DUTY_HOURS = 10
CYCLE_LIMIT_HOURS = 70
CYCLE_RESET_HOURS = 34  
DAY_HOURS = 24

__all__ = [
	"FUEL_INTERVAL_MILES",
	"FUEL_STOP_HOURS",
	"PICKUP_DROP_HOURS",
	"AVG_SPEED_MPH",
	"DAILY_MAX_ON_DUTY",
	"DAILY_MAX_DRIVING",
	"OFF_DUTY_HOURS",
	"CYCLE_LIMIT_HOURS",
	"CYCLE_RESET_HOURS",
	"DAY_HOURS"
]
