# Generated by Django 5.0.4 on 2025-11-08 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('current_location_coords', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_coords', models.CharField(blank=True, max_length=100, null=True)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_coords', models.CharField(blank=True, max_length=100, null=True)),
                ('current_cycle_used', models.FloatField(default=0.0, help_text='Hours already used in current cycle')),
                ('total_trip_hours', models.FloatField(blank=True, null=True)),
                ('total_distance_km', models.FloatField(blank=True, null=True)),
                ('route_geojson', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('hours_driven', models.FloatField(default=0.0)),
                ('rest_time', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sheet_image', models.ImageField(blank=True, null=True, upload_to='logs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trips.trip')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('trip', 'day_number')},
            },
        ),
    ]
