# Generated by Django 5.0.4 on 2025-11-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logsheet',
            options={'ordering': ['day_number'], 'verbose_name': 'Log Sheet', 'verbose_name_plural': 'Log Sheets'},
        ),
        migrations.AlterField(
            model_name='logsheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='logsheet',
            name='day_number',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='logsheet',
            index=models.Index(fields=['trip', 'day_number'], name='trips_logsh_trip_id_389798_idx'),
        ),
        migrations.AddIndex(
            model_name='logsheet',
            index=models.Index(fields=['created_at'], name='trips_logsh_created_94ed0a_idx'),
        ),
    ]
